const ShopActionTypes = {
  FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
  FETCH_COLLECTIONS_FAIL: 'FETCH_COLLECTIONS_FAIL',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  UPDATE_COLLECTIONS: 'UPDATE_COLLECTIONS',
}

export default ShopActionTypes
